DROP TABLE IF EXISTS sensorData;

CREATE TABLE sensorData (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    sensorType TEXT NOT NULL,
    sensorValue TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);